# Remap prefix 
unbind C-b
set-option -g prefix C-Space
bind C-Space send-prefix

# Split panes 
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# Reload config file
bind r source-file "$HOME/.config/tmux/tmux.conf" \; display-message "Config reloaded!"

# Switch panes using Alt+h/j/k/l
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Enable mouse mode
set -g mouse on

# Stop auto renaming windows
set-option -g allow-rename off

# DESIGN TWEAKS

# Panes
set -g pane-border-style "fg=#5c6370"
set -g pane-active-border-style "fg=#e954a4"

# Status bar
set -g status-position bottom
set -g status-justify left
set -g status-style "bg=#2b2b2b,fg=#d8d8d8"

set -g status-left ""
set -g status-left-length 10

set -g status-right "#[fg=#2b2b2b,bg=#e954a4] %Y-%m-%d %H:%M "
set -g status-right-length 50

# Windows
setw -g window-status-style "fg=#8a8a8a,bg=#2b2b2b"
setw -g window-status-format " #I #W "

setw -g window-status-current-style "fg=#ffffff,bg=#e954a4,bold"
setw -g window-status-current-format " #I #W "

setw -g window-status-bell-style "fg=#ffffff,bg=#dd4814,bold"

# Messages
set -g message-style "fg=#ffffff,bg=#e954a4,bold"

# Copy mode
setw -g mode-style "fg=#ffffff,bg=#e954a4"	
